### ISSUE TITLE
No setup for tasks/c++/easy/sum.cpp

### ISSUE THREAD

**Issue by NikolaM4** [fork-commit-merge/fork-commit-merge#2061]
**Describe the bug**
Task is considered easy, but iostream isn't included nor main function exist. For someone who is absolute beginner, that should be included, as it is in other c++ easy tasks.

**Expected behavior**
At least those 2 things should be included, but I suggest adding also "using namespace std;" because beginners don't know what all of that means and they would probably like just to use cout to display sum of 2 numbers.

**Screenshots**
![image](https://github.com/fork-commit-merge/fork-commit-merge/assets/128964319/d60129ee-8629-416e-abbb-afc52a6f0349)

**Comment by nikohoffren** [comment]
> **Describe the bug** Task is considered easy, but iostream isn't included nor main function exist. For someone who is absolute beginner, that should be included, as it is in other c++ easy tasks.
> 
> **Expected behavior** At least those 2 things should be included, but I suggest adding also "using namespace std;" because beginners don't know what all of that means and they would probably like just to use cout to display sum of 2 numbers.
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/128964319/301861359-d60129ee-8629-416e-abbb-afc52a6f0349.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODg5MDksIm5iZiI6MTcwNjg4ODYwOSwicGF0aCI6Ii8xMjg5NjQzMTkvMzAxODYxMzU5LWQ2MDEyOWVlLTg2MjktNDE2ZS1hYmJiLWFmYzUyYTZmMDM0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxNTQzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzAwZmQxMTk5NGZjMTg1ZDUwNDU3OWM0MzllNTZmY2QyODg5NjAzZjk2ZmEwM2U1MjAyNTZiYmU5MzcwNjY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.olnJVzvw4wR4EDuaGc0LIi9lkWwhQYIzroEUSvdb7Ns)

Sounds good, you can make a pull request with those changes and i can merge it without reverting the changes.
